"""diabetes_record_outcome_nullable

Revision ID: 2878ebf4ec41
Revises: 5c59c1e598b5
Create Date: 2025-06-12 03:24:26.513750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2878ebf4ec41'
down_revision: Union[str, None] = '5c59c1e598b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diabetes_records', 'pregnancies',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('diabetes_records', 'outcome',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='Whether the person has diabetes (1 = yes, 0 = no)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diabetes_records', 'outcome',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='Whether the person has diabetes (1 = yes, 0 = no)')
    op.alter_column('diabetes_records', 'pregnancies',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
