"""initial

Revision ID: 532c0f22ab3a
Revises: 
Create Date: 2025-06-09 15:26:15.100801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '532c0f22ab3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('records_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diabetes_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregnancies', sa.Integer(), nullable=True),
    sa.Column('glucose', sa.Integer(), nullable=False),
    sa.Column('blood_pressure', sa.Integer(), nullable=True),
    sa.Column('skin_thickness', sa.Integer(), nullable=True),
    sa.Column('insulin', sa.Integer(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=False),
    sa.Column('diabetes_pedigree', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Boolean(), nullable=True),
    sa.Column('source', sa.Enum('DATASET', 'USER_UPLOAD', name='datasource'), nullable=False),
    sa.Column('user_attempt_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_attempt_id'], ['user_attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diabetes_records_id'), 'diabetes_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diabetes_records_id'), table_name='diabetes_records')
    op.drop_table('diabetes_records')
    op.drop_table('user_attempts')
    # ### end Alembic commands ###
