"""fix_health_assessment_relationships

Revision ID: 5c59c1e598b5
Revises: d52fbc48d9be
Create Date: 2025-06-10 01:52:46.161741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c59c1e598b5'
down_revision: Union[str, None] = 'd52fbc48d9be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_assessments', sa.Column('diabetes_record_id', sa.Integer(), nullable=False))
    op.alter_column('health_assessments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('health_assessments', 'recommendations',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('health_assessments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('health_assessments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_health_assessments_id'), 'health_assessments', ['id'], unique=False)
    op.create_foreign_key(None, 'health_assessments', 'diabetes_records', ['diabetes_record_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health_assessments', type_='foreignkey')
    op.drop_index(op.f('ix_health_assessments_id'), table_name='health_assessments')
    op.alter_column('health_assessments', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('health_assessments', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('health_assessments', 'recommendations',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('health_assessments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('health_assessments', 'diabetes_record_id')
    # ### end Alembic commands ###
